language: c
dist: bionic

env:
  global:
    - CC=gcc-9
    - CXX=g++-9
  matrix:
    - SMVERSION=1.10
    - SMVERSION=1.11

matrix:
  fast_finish: true

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib lib32stdc++6 lib32z1 lynx gcc-9 g++-9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9

script:
  - ./compile.sh

notifications:
  email: false
